### ISSUE TITLE
Fibocom L860R+ on P14s Gen 4 AMD

### ISSUE THREAD

**Issue by wolfwood** [lenovo/lenovo-wwan-unlock#10]
is this support planned? 

Thanks!

**Comment by nitinexclusively** [comment]
Hello @wolfwood  Sorry for late reply ! 
Thanks for letting me know that P14s Gen 4 is of interest .
As of now, support to enable WWAN on P14s is not planned  but i have noted it.
I will  update, if there is any change of plan in future.

Thanks

**Comment by nitinexclusively** [comment]
Let me close this ticket for now.
