### ISSUE TITLE
Support Quectel EM160R-GL on ThinkPad P15s Gen 2i

### ISSUE THREAD

**Issue by johnstray** [lenovo/lenovo-wwan-unlock#12]
I am the proud owner of a ThinkPad P15s Gen 2i with an in-built Quectel EM160R-GL (pci:1eac:1002) wwan modem and running Fedora Linux 40. This is to be used with an Australian SIM in Australia only.

I would **_really really really appreciate_** support for my setup so I can finally have usable wwan, this is an extremely important necessity for me.

I am willing and able to perform the modifications to the software myself if possible, but the source for the 'configservice_lenovo' binary are not on this github page. If I can do this, I can then live test and post back the modified version with support for this setup.

I am strongly against hardware level locking of devices preventing users from using the hardware that they have bought and paid for and therefore own, especially when realisticly there is no technical reason for there to be such an unnecessary block. The FCC rules apply to the US only, not Australia.

So, I would like to have my wwan device up and running as soon as practically possible! Thanks!

**Comment by nitinexclusively** [comment]
Hello @johnstray - Thank you for reaching out and apologize for late reply.
As of now, there is no plan to support Quectel EM160R-GL on a ThinkPad P15s Gen 2i for Linux .

I can understand your concern but this is as per requirement. So, we need to comply with it. 
Thank you !

**Comment by nitinexclusively** [comment]
Let me close this ticket

**Comment by johnstray** [comment]
THIS IS NOT GOOD ENOUGH! 

I NEED THIS WORKING NOW!

**Comment by lxwulf** [comment]
> THIS IS NOT GOOD ENOUGH! 
> 
> I NEED THIS WORKING NOW!

@johnstray please get your tone right! The procedure is complicated and not as easy as you may think. As @nitinexclusively already mentioned, there is no plan at the moment to do so. Maybe there is help in a Linux forum for your situation; else, a 4G or 5G USB router should work out of the box, as far as I know, though not everyone will work.

Anyway, please be nice and respectful. Thank you.

**Comment by johnstray** [comment]
Allow me to re-iterate... The FCC rules apply to the US only, not Australia, so there is no requirement.

I have bought, paid for and own my laptop. I should be able to use all of its functions, including and especially the wwan device it includes.

I, along with many others around the world, are extremely frustrated with Lenovo's very poor support for Linux with these wwan devices.

For a little while I was able to get it working (sort of) with a workaround that was included with ModemManager, however this no-longer seems to be working. So I am back here again (almost 2 years later) seeking to have this device fully supported, as it should have been when I first purchased it.

If you are unwilling to do so, then maybe you can point me in the direction of a method that would work, but if not, as much as I've liked Lenovo laptops, I may have to instead look elsewhere, somewhere that doesn't do unnecessary restrictions like this.

My apologies if my tone seems to be quite harsh and forward, but as I'm sure you can understand, I am extremely frustrated with the lack of a working wwan device.
