### ISSUE TITLE
[Question] Plans to create an uninstallation routine?

### ISSUE THREAD

**Issue by lxwulf** [lenovo/lenovo-wwan-unlock#15]
# Explanation

Maybe I have installed another card with other needed configuration. 
So I require a clean driver environment again.

Are there any plans to create also an uninstallation routine?

**Comment by nitinexclusively** [comment]
@lxwulf Thanks for your comments . Yes, i am planning to release script to uninstall package soon . Thanks

**Comment by nitinexclusively** [comment]
Released uninstall script https://github.com/lenovo/lenovo-wwan-unlock/commit/6927832edf629ffe98d16eaa66ec57b402a2781a
Thanks

**Comment by lxwulf** [comment]
I just wanted to say many thanks for this fast and accurate addition to the project!
