### ISSUE TITLE
Problem with EM061K-GL on T14s G5

### ISSUE THREAD

**Issue by galibozek** [lenovo/lenovo-wwan-unlock#16]
I have a problem with establishing a connection using Quectel EM061K-GL on T14s G5.
The modem registers on the network 
```
  -----------------------------------
  Status   |                    lock: sim-pin2
           |          unlock retries: sim-pin2 (3)
           |                   state: registered

```
but does not connect, connecting state over and over again....

It looks like it has the wrong `carrier config` set, in my opinion it should be `ROW_Commercial`.
```
  -----------------------------------
  Hardware |            manufacturer: Quectel
           |                   model: EM061K-GL
           |       firmware revision: EM061KGLAAR01A02M2G
           |          carrier config: Commercial-DT-VOLTE
           | carrier config revision: 08011F1F
           |            h/w revision: EM061K-GL
```

I could change it with AT commands, but it looks like the serial port is not available (disabled by lenovo?) :/
How can this be changed?

(On Windows same problem, I updated the firmware but it did not change the profile)

**Comment by nitinexclusively** [comment]
Can you please retry after inputting below command with correct APN information and reboot machine ?
**mmcli -m 0 --3gpp-set-initial-eps-bearer-settings=apn=xxxx,ip-type=IPV4V6,allowed-auth=chap,user=xxxx,password=xxxx**

Please replace "xxxx" in above command with correct information.

Also , can you please attached output of below commands after reboot:
- cat /var/log/syslog | grep -i dpr_fcc
- mmcli -m any

Thank you

**Comment by galibozek** [comment]
Thanks, works, after run

`mmcli -m 0 --3gpp-set-initial-eps-bearer-settings=apn=internet,ip-type=IPV4V6,allowed-auth=chap`
