### ISSUE TITLE
Support for ThinkPad X1 Extreme 3rd Gen with L-860

### ISSUE THREAD

**Issue by muhackel** [lenovo/lenovo-wwan-unlock#19]
Are there any plans to support my seasoned system?
I'm waiting for Linux WWAN Support since the machine came out.

**Comment by muhackel** [comment]
Well here ist the abriged version of systemctl status lenovo-cfgservice.service.

`configservice_lenovo[1081]: WWAN is not supported in this machine`

Seems like there are checks in place.

**Comment by nitinexclusively** [comment]
@muhackel Thanks for reaching out . As of now, we don't have any plan to officially support X1 Extreme 3rd Gen.
Enablement is done on a platform/modem combination. There are a number of extra system unique tests that take time and are required (RF testing etc). We haven't been able to enable WWAN for the whole Linux certified portfolio and the X1 Extreme 3rd Gen was not in the initial group approved.
Thanks for letting us know the X1 Extreme 3rd Gen would be of interest!

**Comment by muhackel** [comment]
Thanks for the answer even if it's not exacty what I hoped for. Interesting thou that the machine and the WWAN module are seperate "Linux Compatible" but not together. 

I know it's the wrong channel but can you tell me if there is a "BIOS Lock" on this machine so i can put in one that is not FCC locked and are there any recomendations?

**Comment by lxwulf** [comment]
@nitinexclusively Is there no possibility to split up the platform in the enablement process to be focused only on the modem? Why is the platform also important? If we could focus on the modem, I think sooner or later we can also contribute this to the Linux community in general. 

Just curious, I really love the hard work on this project, I'm looking forward to this. 😊

**Comment by nitinexclusively** [comment]
@lxwulf  Sorry for my late reply.
>Is there no possibility to split up the platform in the enablement process to be focused only on the modem? Why is the platform also important?


Platform is also important. WWAN enablement is done in the combination for Platform and WWAN Modem in order to be FCC compliant . Each combination of platform and WWAN modem has to FCC compliant by setting correct SAR config value which is verified during RF testing.
I hope this answer your question. Thanks

**Comment by lxwulf** [comment]
@nitinexclusively No need to, sorry. Many thanks for your detailed answer! With this knowledge it makes much more sense why not every product is supported despite the WWAN module is supported.

I would like to suggest adding this information into the README, so everyone know exactly why their device may not be supported yet.

Is there a way to speed up the process and help us together, so more devices and models get supported? 😊

Anyway, many thanks again for sharing knowledge with us! 🤝

**Comment by nitinexclusively** [comment]
@lxwulf Thank you for your suggestion. I will add it in README.
> Is there a way to speed up the process and help us together, so more devices and models get supported? 😊
 As of now , we are working on new modem's . So , pushing for this will not help much as it will require some cost and resource. I will definitely update , if any information is required. 

let me close this ticket. Please feel free to comment or reopen in case of any concern or comments.
Thank you !

**Comment by muhackel** [comment]
One year+ later, i'll still ask the same question ... are there any plans to support "older" models like my X1 Extrem Gen3 or do i own a moderate old wwan brick? 
To be honest, the SAR config values should be known (i bet the windows driver needs them too) so unlocking of the WWAN module should be a solved problem.

**Comment by lxwulf** [comment]
> One year+ later, i'll still ask the same question ... are there any plans to support "older" models like my X1 Extrem Gen3 or do i own a moderate old wwan brick? To be honest, the SAR config values should be known (i bet the windows driver needs them too) so unlocking of the WWAN module should be a solved problem.

As already mentioned, the driver is the least problem. The FCC compliance is the process which takes many resources and time. This time though is better used for newer models which are already in the development process, so it takes much less resources than to recertify older models. I hope I could explain it a bit better.
