### ISSUE TITLE
Support for P16 Gen2

### ISSUE THREAD

**Issue by lesong36** [lenovo/lenovo-wwan-unlock#20]
Hi, 

I had issue with Wwan on ubuntu 24.04. Below is my info. Could you please help me check.

(base) coty@P16:~$ uname -a
Linux P16 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
(base) coty@P16:~$ NetworkManager --version
1.46.0
(base) coty@P16:~$ ModemManager --version
ModemManager 1.23.4
Copyright (C) 2008-2023 The ModemManager authors
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

(base) coty@P16:~$ mmcli -m any
  ----------------------------------
  General  |                   path: /org/freedesktop/ModemManager1/Modem/2
           |              device id: 53ca2e332d36a0cc44e3c4e7bb0d95bfef8b91b5
  ----------------------------------
  Hardware |           manufacturer: Intel
           |                  model: MBIM [8086:7560]
           |      firmware revision: 18601.5001.00.01.17.30_GC
           |           h/w revision: V1.3
           |              supported: gsm-umts, lte
           |                current: gsm-umts, lte
           |           equipment id: 016175007389028
  ----------------------------------
  System   |                 device: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0
           |                physdev: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0
           |                drivers: iosm
           |                 plugin: Intel
           |           primary port: wwan0mbim0
           |                  ports: wwan0 (net), wwan0at0 (at), wwan0at1 (at), wwan0mbim0 (mbim)
  ----------------------------------
  Numbers  |                    own: +01117310696682
  ----------------------------------
  Status   |         unlock retries: sim-pin (3)
           |                  state: enabling
           |            power state: low
  ----------------------------------
  Modes    |              supported: allowed: 3g, 4g; preferred: none
           |                current: allowed: 3g, 4g; preferred: none
  ----------------------------------
  IP       |              supported: ipv4, ipv6, ipv4v6
  ----------------------------------
  3GPP     |                   imei: 01617500738xxxx
           |          enabled locks: fixed-dialing
  ----------------------------------
  3GPP EPS |   ue mode of operation: csps-2
           | initial bearer ip type: ipv4v6
  ----------------------------------
  SIM      |       primary sim path: /org/freedesktop/ModemManager1/SIM/3
           |         sim slot paths: slot 1: /org/freedesktop/ModemManager1/SIM/3 (active)
           |                         slot 2: /org/freedesktop/ModemManager1/SIM/4

(base) coty@P16:~$ mbimcli -p -d /dev/wwan0mbim0 -v --quectel-query-radio-state
[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] opening device...
[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] couldn't find descriptors file, possibly not using cdc_mbim
[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] fallback to default max control message size: 4096
[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] sent message...
<<<<<< RAW:
<<<<<<   length = 92
<<<<<<   data   = 03:00:00:00:5C:00:00:00:01:00:00:00...

[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] sent message (translated)...
<<<<<< Header:
<<<<<<   length      = 92
<<<<<<   type        = command (0x00000003)
<<<<<<   transaction = 1
<<<<<< Fragment header:
<<<<<<   total   = 1
<<<<<<   current = 0
<<<<<< Contents:
<<<<<<   service = 'proxy-control' (838cf7fb-8d0d-4d7f-871e-d71dbefbb39b)
<<<<<<   cid     = 'configuration' (0x00000001)
<<<<<<   type    = 'set' (0x00000001)
<<<<<< Fields:
<<<<<<   DevicePath = '/dev/wwan0mbim0'
<<<<<<   Timeout = '30'

[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] unexpected port hangup!
[15 Aug 2024, 00:46:26] [Debug] [/dev/wwan0mbim0] channel destroyed
[15 Aug 2024, 00:46:56] [Debug] [/dev/wwan0mbim0] number of consecutive timeouts: 1
[15 Aug 2024, 00:46:56] [Debug] [/dev/wwan0mbim0] proxy configuration failed: closed
error: couldn't open the MbimDevice: Transaction timed out
(base) coty@P16:~$ mmcli --modem 0 --enable
error: couldn't find modem

(base) coty@P16:~$ lspci | grep "Wireless controller"
08:00.0 Wireless controller [0d40]: Intel Corporation XMM7560 LTE Advanced Pro Modem (rev 01)
(base) coty@P16:~$ mmcli --modem 0 --enable
error: couldn't find modem
(base) coty@P16:~$ systemctl status lenovo-cfgservice.service
○ lenovo-cfgservice.service - sar config
     Loaded: loaded (/etc/systemd/system/lenovo-cfgservice.service; enabled; preset: enabled)
     Active: inactive (dead) since Thu 2024-08-15 00:33:12 CST; 19min ago
   Duration: 15ms
   Main PID: 1365 (code=exited, status=0/SUCCESS)
        CPU: 2ms

**Comment by nitinexclusively** [comment]
Hi @lesong36  Thank you for reaching out and apologize for late reply.
I can see you are using P16Gen2 which is not officially supported as of now https://github.com/lenovo/lenovo-wwan-unlock/blob/main/README.md and also, there is no plan to support L860R+ on P16 Gen 2  .
> mmcli --modem 0 --enable
error: couldn't find modem

I think you need to check correct Modem number using "mmcli -L" , Maybe its not 0 and you need to give 2 for example **mmcli --modem 2 --enable**
Thanks

**Comment by lesong36** [comment]
> mmcli -L



> Hi @lesong36 Thank you for reaching out and apologize for late reply. I can see you are using P16Gen2 which is not officially supported as of now https://github.com/lenovo/lenovo-wwan-unlock/blob/main/README.md and also, there is no plan to support L860R+ on P16 Gen 2 .
> 
> > mmcli --modem 0 --enable
> > error: couldn't find modem
> 
> I think you need to check correct Modem number using "mmcli -L" , Maybe its not 0 and you need to give 2 for example **mmcli --modem 2 --enable** Thanks

Thank you for the response, although it’s not exactly what I was hoping for. It is interesting, however, that the machine and the WWAN module are both 'Linux Compatible,' but not when used together.

I check the Modern number and it is indeed 0.

(base) coty@P16:~$ mmcli -L
    /org/freedesktop/ModemManager1/Modem/0 [Intel] MBIM [8086:7560]
(base) coty@P16:~$ mmcli --modem 0 --enable
error: couldn't enable the modem: 'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.Retry: Retry: Invalid transition'

**Comment by nitinexclusively** [comment]
I haven't tried it as we are working in newer modems. Do you have any success on this ? Thanks

**Comment by lesong36** [comment]
> I haven't tried it as we are working in newer modems. Do you have any success on this ? Thanks

no, still waiting official support.

**Comment by lesong36** [comment]
> I haven't tried it as we are working in newer modems. Do you have any success on this ? Thanks

**Comment by smthtian** [comment]
is ther any plan to support for P1 gen 5, FM350-GL?

**Comment by lxwulf** [comment]
> is ther any plan to support for P1 gen 5, FM350-GL?

It is not listed in the README.md file, so probably not. Spamming the same question in different issue/support post will not help to consider the model support or speed up the development of it. If you want a real answer, please create a new `issue post`.

**Please refrain from such spamming behavior in the future. This will be not tolerated.**

Thank you

**Comment by nitinexclusively** [comment]
Let me close this ticket . Please reopen or open new ticket , if you have any issue . Thank you !
