### ISSUE TITLE
[Question] P14s AMD Gen1 Fibocom L850-GL support

### ISSUE THREAD

**Issue by checkoutmyvaldis** [lenovo/lenovo-wwan-unlock#21]
Is there a plan to add support for the device mentioned in the title?

Currently having no luck with this:
[https://github.com/xmm7360/xmm7360-pci](url)

**Comment by nitinexclusively** [comment]
@checkoutmyvaldis  Thank you for reaching out .Sorry, we dont have any plan to support it.
Thanks

**Comment by yummy527** [comment]
I have a Carbon Gen 8 with Fibocom L850-GL(xmm 7360) too. And xmm7360-pci does not works well on my machine. 
It seems that this modem is not easy to work elegantly in Linux. 😢

**Comment by nitinexclusively** [comment]
Hello @yummy527 Sorry for late reply ! We had not supported this module officially . If you have have other question , please feel free to let us know ! Closing this ticket , thank you !
