### ISSUE TITLE
RM520N-GL could not work on T14 Gen 5 

### ISSUE THREAD

**Issue by binli** [lenovo/lenovo-wwan-unlock#25]
lenovo 2.1.2 from https://launchpad.net/~lenovo-oem/+archive/ubuntu/wwan/

08:00.0 Unassigned class [ff00]: Quectel Wireless Solutions Co., Ltd. Device [1eac:1007]
→       Subsystem: Quectel Wireless Solutions Co., Ltd. Device [1eac:100a]

Sep 29 04:28:22 Matterhorn-2 DPR_Fcc_unlock_service[2519]: WWAN device Quectel RM520N-GL found
Sep 29 04:28:22 Matterhorn-2 DPR_Fcc_unlock_service[2519]: Device "/dev/wwan0mbim0" exists
Sep 29 04:28:22 Matterhorn-2 DPR_Fcc_unlock_service[2519]: SIM inserted is of non-USA
Sep 29 04:28:22 Matterhorn-2 DPR_Fcc_unlock_service[2519]: FCC unlock is success
Sep 29 04:28:22 Matterhorn-2 DPR_Fcc_unlock_service[2519]: FCC unlock app exited
Sep 29 04:28:22 Matterhorn-2 systemd[1]: lenovo-fccunlock.service: Deactivated successfully.
Sep 29 04:28:22 Matterhorn-2 systemd[1]: Finished fccunlock.
Sep 29 04:28:22 Matterhorn-2 sudo[2515]: pam_unix(sudo:session): session closed for user root
Sep 29 04:28:25 Matterhorn-2 ModemManager[938]: <warn>  [modem1] port wwan0at0 timed out 8 consecutive times
Sep 29 04:28:28 Matterhorn-2 ModemManager[938]: <warn>  [modem1] port wwan0at0 timed out 9 consecutive times
Sep 29 04:28:31 Matterhorn-2 ModemManager[938]: <error> [modem1] port wwan0at0 timed out 10 consecutive times, marking modem as invalid
Sep 29 04:28:31 Matterhorn-2 ModemManager[938]: <warn>  [modem1] couldn't set version: Unknown revision
Sep 29 04:28:31 Matterhorn-2 ModemManager[938]: <warn>  [modem1] error initializing: Operation was cancelled
Sep 29 04:28:35 Matterhorn-2 ModemManager[938]: <warn>  [/dev/wwan0mbim0] MBIM error: Transaction timed out
Sep 29 04:28:35 Matterhorn-2 ModemManager[938]: <warn>  [/dev/wwan0mbim0] MBIM error: Transaction timed out
Sep 29 04:28:35 Matterhorn-2 ModemManager[938]: <warn>  [/dev/wwan0mbim0] MBIM error: Transaction timed out
Sep 29 04:28:35 Matterhorn-2 ModemManager[938]: <warn>  [/dev/wwan0mbim0] MBIM error: Transaction timed out
Sep 29 04:28:35 Matterhorn-2 ModemManager[938]: <warn>  [/dev/wwan0mbim0] MBIM error: Transaction timed out
Sep 29 04:28:37 Matterhorn-2 ubuntu-report[1633]: level=error msg="data were not delivered successfully to metrics server, retrying in 120s"
Sep 29 04:29:08 Matterhorn-2 systemd[1622]: Started Application launched by gnome-session-binary.

**Comment by binli** [comment]
@nitinexclusively is T14 Gen5 supported in your code?

**Comment by binli** [comment]
SIM inserted is of non-USA, does it mean the fccunlock could not unlock the country?

**Comment by nitinexclusively** [comment]
> @nitinexclusively is T14 Gen5 supported in your code?

Yes , its supported . Please refer https://github.com/lenovo/lenovo-wwan-unlock/blob/main/README.md  for supported product and modem

**Comment by nitinexclusively** [comment]
> SIM inserted is of non-USA, does it mean the fccunlock could not unlock the country?

FCC unlock is not enabled for USA SIM . Reason of this that we need Carrier certification for USA operators and this is still under discussion and may take months . So, we have disable FCC unlock for USA SIM for now.

**Comment by nitinexclusively** [comment]
Looks similar to https://github.com/lenovo/lenovo-wwan-unlock/issues/28
hence closing this issue. Thanks
