### ISSUE TITLE
RM520N-GL could not work on P16v Gen 2

### ISSUE THREAD

**Issue by binli** [lenovo/lenovo-wwan-unlock#26]
P16v has RM520N-GL, but I could not use the fccunlock. Could we add this machine in supported list?

08:00.0 Unassigned class [ff00]: Quectel Wireless Solutions Co., Ltd. Device [1eac:1007]
→       Subsystem: Quectel Wireless Solutions Co., Ltd. Device [1eac:1009]

Sep 29 04:40:24 oak2-10 systemd[1]: Starting fccunlock...
Sep 29 04:40:24 oak2-10 DPR_Fcc_unlock_service[2642]: FCC unlock app started 2.0.0
Sep 29 04:40:24 oak2-10 DPR_Fcc_unlock_service[2642]: WWAN is not supported in this machine
Sep 29 04:40:24 oak2-10 systemd[1]: lenovo-fccunlock.service: Deactivated successfully.
Sep 29 04:40:24 oak2-10 systemd[1]: Finished fccunlock.
Sep 29 04:40:24 oak2-10 sudo[2638]: pam_unix(sudo:session): session closed for user root
Sep 29 04:40:28 oak2-10 systemd[1717]: Started Application launched by gnome-session-binary.
Sep 29 04:40:28 oak2-10 systemd[1717]: Started Application launched by gnome-session-binary.
Sep 29 04:40:29 oak2-10 ubuntu-appindicators@ubuntu.com[1902]: unable to update icon for software-update-available
Sep 29 04:40:29 oak2-10 ubuntu-appindicators@ubuntu.com[1902]: unable to update icon for livepatch

**Comment by nitinexclusively** [comment]
We dont have plan to support P16v Gen 2 as of now .
Enablement is done on a platform/modem combination. There are a number of extra system unique tests that take time and are required (RF testing etc). We haven't been able to enable WWAN for the whole Linux certified portfolio and the P16v G2 was not in the initial group approved.
We're looking to extend the scope, now we have it working on some platforms, but have to balance it against resources available. We and are doing that based on demand and what the test teams can accommodate.
Thanks for letting us know the P16v G2 would be of interest!

Thanks

**Comment by binli** [comment]
Got it, I want find another available laptop to test 1eac:1007 wwan.
P14s Gen 5  AMD also  prompts 'WWAN is not supported in this machine'
So I thought it should be same reason.
