### ISSUE TITLE
Status of Thinkpad P1 Gen 6?

### ISSUE THREAD

**Issue by jrelvas-ipc** [lenovo/lenovo-wwan-unlock#3]
According to [this spec sheet](https://thinkstation-specs.com/thinkpad/p1-gen-6/#section2_wwan), the P1 gen 6 has a `Fibocom L860-GL-16 4G CAT16` WWAN, which seems to be one referred to in README.

![imagem](https://github.com/lenovo/lenovo-wwan-unlock/assets/55360900/a5f4b22a-351e-4ad7-aa37-2744409aedd8)

However, it's not listed as a supported system. Is this unlock something that is done per wwan device, or is it a process which needs to be done for every individual system/platform? Asking in case it was omitted by accident.

**Comment by nitinexclusively** [comment]
Enablement is done on a platform/modem combination. There are a number of extra system unique tests that take time and are required (RF testing etc). We haven't been able to enable WWAN for the whole Linux certified portfolio and the P1 G6 was not in the initial group approved.
We're looking to extend the scope, now we have it working on some platforms, but have to balance it against resources available. We and are doing that based on demand and what the test teams can accommodate.
Thanks for letting us know the P1G6 would be of interest!

**Comment by Noted-Jrelvas** [comment]
I've proposed #4 to avoid future confusion :)

**Comment by nitinexclusively** [comment]
Let me close this issue. Thank you very much !
