### ISSUE TITLE
Why unconfined execute for ps?

### ISSUE THREAD

**Issue by setharnold** [lenovo/lenovo-wwan-unlock#31]
https://github.com/lenovo/lenovo-wwan-unlock/blob/4f8e19e6f7d324decc0842e947dab2ad2bca556d/debian/opt.fcc_lenovo.configservice_lenovo#L17

https://github.com/lenovo/lenovo-wwan-unlock/blob/4f8e19e6f7d324decc0842e947dab2ad2bca556d/debian/opt.fcc_lenovo.DPR_Fcc_unlock_service#L18

Why is the `ps` program given an unconfined execute permission? This is way too broad. Please change this to a `cx` rule or `Cx` rule, as necessary.

Thanks

**Comment by nitinexclusively** [comment]
@setharnold Thanks ! I will need Binli's comment on this .
@binli - Can you please update your comment ? Thanks

**Comment by binli** [comment]
@setharnold thanks for review, fixed it.

**Comment by nitinexclusively** [comment]
Merged fix in ubuntu OEM branch -> https://github.com/lenovo/lenovo-wwan-unlock/tree/ubuntu-oem
Thanks
