### ISSUE TITLE
X1 Carbon Gen 12 with Quectel EM05-CN

### ISSUE THREAD

**Issue by wagdav** [lenovo/lenovo-wwan-unlock#38]
Hello,

I installed a Quectel EM05-CN WWAN module in my X1 Carbon Gen 12.  According to the README, this module and the specific X1 model are compatible. Unfortunately, during boot time the computer displays the error "1802 Unauthorized network card is plugged in" error message. For reference, the error message also displays the code 2C7C/0127.

Note: I haven't run the lenov-wwan-unlock script yet. I was planning to run it with the module installed.

**Comment by nitinexclusively** [comment]
Hello @wagdav It looks your WWAN module is **EM05-CE** 2c7c:0127 and its not **EM05-CN** 2c7c:0310.  
There is no EM05-CE support for X1CG12 , hence you can see this error.
Thanks

**Comment by wagdav** [comment]
Argh, I must have messed up the part numbers. 🤦

Thanks and sorry for the noise!
