### ISSUE TITLE
Will it work on Windows?

### ISSUE THREAD

**Issue by smorkgl** [lenovo/lenovo-wwan-unlock#40]
Hello!

How do I make this work on Windows?

**Comment by lxwulf** [comment]
Hey there 👋,

As far as I know, you don't need any special actions on Windows. This repository here is just for Linux distributions. 

On Windows, it should work with an updated system.

**Comment by nitinexclusively** [comment]
I have same comments as @lxwulf , Thanks for your comments !
Let me close this ticket !
